/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.statistic;

import common_function.UI;
import controller.BookingDAO;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.time.Duration;
import model.RoomStat;
import model.User;
import java.util.Date;
import javax.swing.table.DefaultTableModel;
import model.Room;
import view.user.LoginFrm;
/**
 *
 * @author LENOVO
 */
public class RoomDetailFrm extends javax.swing.JFrame implements ActionListener{

    /**
     * Creates new form RoomDetailFrm
     */
    
    private User user;
    private Room room;
    private Date startDate;
    private Date endDate;
    public RoomDetailFrm(User user,Room room,Date startDate,Date endDate) {
        initComponents();
        this.user = user;
        this.room = room;
        this.startDate = startDate;
        this.endDate = endDate;
        
        //UI
        setTitle("Hotel Management System - Detail Room Statistic");
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        this.getContentPane().setBackground(Color.getHSBColor(106, 52, 50));
        UI.setFontForLabel(jLabel1);
        UI.setFontForLabel(jLabel2);
        UI.setFontForLabel(jLabel3);
        UI.setFontForLabel(labelEndDate);
        UI.setFontForLabel(labelStartDate);
        UI.setFontForLabel(labelRoomName);
        UI.setFontForLabel(jLabel3);
        UI.setFontForLabel(txtRoleLabel);
        UI.setFontForLabel(txtUserLabel);
        txtUserFullName.setText(user.getFullName());
        txtRole.setText(user.getPosition());
        btnLogOut.addActionListener((e) -> {
            (new LoginFrm()).setVisible(true);
            this.dispose();
        });
        
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        labelStartDate.setText(sdf.format(startDate));
        labelEndDate.setText(sdf.format(endDate));
        labelRoomName.setText(room.getName());
        
        
        BookingDAO bookingDAO = new BookingDAO();
        var listBookings = bookingDAO.getBookingOfRoom(room.getID(), startDate, endDate);
        //hien thi list booking cho nguoi dung
           
            String[][] data = new String[listBookings.size()][7];
            for (int i = 0; i < listBookings.size(); i++) {
                var roomStat = listBookings.get(i);
                data[i][0] = (i+1)+"";
                data[i][1] = roomStat.getClient().getFullName();
                Date checkin = roomStat.getBookedRooms().get(0).getCheckIn();
                Date checkout = roomStat.getBookedRooms().get(0).getCheckOut();
                data[i][2] = sdf.format(checkin);
                data[i][3] = sdf.format(checkout);
                float price = roomStat.getBookedRooms().get(0).getPrice();
                data[i][4] =price+"";
                int totalDays = (int)(checkout.getTime()-checkin.getTime())/(1000*60*60*24);
                data[i][5] = totalDays+"";
                data[i][6] = totalDays*price+"";
            }
            String[] columnNames = {"No","Client Name","Check in","Check out","Price","Total days","Total revenue"};
            DefaultTableModel dtm = new DefaultTableModel(data, columnNames);
            tblBill.setModel(dtm);
            
            
            btnBack.addActionListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblBill = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        txtUserLabel = new javax.swing.JLabel();
        txtUserFullName = new javax.swing.JLabel();
        txtRoleLabel = new javax.swing.JLabel();
        txtRole = new javax.swing.JLabel();
        btnLogOut = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        labelRoomName = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        labelEndDate = new javax.swing.JLabel();
        labelStartDate = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblBill.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Client name", "Check in", "Check out", "Price", "Total days", "Total revenue"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.Integer.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblBill);

        btnBack.setText("<---");

        txtUserLabel.setText("User:");

        txtUserFullName.setText("jLabel6");

        txtRoleLabel.setText("Role:");

        txtRole.setText("jLabel7");

        btnLogOut.setText("Log out");

        jLabel1.setText("Clients Who Stays In Room");

        labelRoomName.setText("jLabel2");

        jLabel2.setText("From");

        jLabel3.setText("To");

        labelEndDate.setText("jLabel4");

        labelStartDate.setText("jLabel4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtUserLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUserFullName, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtRoleLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtRole, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 841, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(34, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelRoomName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)
                                .addGap(22, 22, 22)
                                .addComponent(labelStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(labelEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(txtUserLabel)
                    .addComponent(txtUserFullName)
                    .addComponent(btnLogOut)
                    .addComponent(txtRoleLabel)
                    .addComponent(txtRole))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelRoomName, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelEndDate;
    private javax.swing.JLabel labelRoomName;
    private javax.swing.JLabel labelStartDate;
    private javax.swing.JTable tblBill;
    private javax.swing.JLabel txtRole;
    private javax.swing.JLabel txtRoleLabel;
    private javax.swing.JLabel txtUserFullName;
    private javax.swing.JLabel txtUserLabel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        (new RoomStatFrm(user)).setVisible(true);
        this.dispose();
    }
}
